### DISCUSSION TITLE
How do I use the targetUpdateIds parameter?

### DISCUSSION THREAD

**Discussion by Ossiam** [mburumaxwell/paklo#1333] [Q&A] [answered]
I have a C# repo containing multiple projects I want to update. That means the dependabot configs for each project will be stored in the same dependabot.yaml, in the root of the repo. 

Example: 

.github/dependabot.yaml
```yaml
  - package-ecosystem: "nuget"
    directory: "/src/project1"

  - package-ecosystem: "npm"
    directory: "/src/project1/client"

  - package-ecosystem: "nuget"
    directory: "/src/project2"
```

Currently in my Azure pipeline, the dependabot task will update these projects serially, one at a time. But I would like to update them in parallel (especially because the pipeline will timeout after 60 min). After reading the description of the "targetUpdateIds" parameter, it seems to achieve what I want, but I wanted to confirm.

Can I simply do the following in my pipeline?

```yaml
stages:
  - stage: 'Project1 Nuget'
    dependsOn: []
    jobs:
      - job:
        steps:
          - task: dependabot@1
            displayName: Update dependencies - Project 1 Nuget
            inputs:
              mergeStrategy: 4
              setAutoComplete: true
              useUpdateScriptvNext: true
              targetRepositoryName: 'Project1'
              targetUpdateIds: '0'

  - stage: 'Project1 Npm'
    dependsOn: []
    jobs:
      - job:
        steps:
          - task: dependabot@1
            displayName: Update dependencies - Project 1 Npm
            inputs:
              mergeStrategy: 4
              setAutoComplete: true
              useUpdateScriptvNext: true
              targetRepositoryName: 'Project1'
              targetUpdateIds: '1'

  - stage: 'Project2 Nuget'
    dependsOn: []
    jobs:
      - job:
        steps:
          - task: dependabot@1
            displayName: Update dependencies - Project 2 Nuget
            inputs:
              mergeStrategy: 4
              setAutoComplete: true
              useUpdateScriptvNext: true
              targetRepositoryName: 'Project1'
              targetUpdateIds: '2'
```
