### DISCUSSION TITLE
[Question] Am I using abandonUnwantedPullRequests Correctly

### DISCUSSION THREAD

**Discussion by matthp4** [mburumaxwell/paklo#1440] [Q&A] [answered]
I wanted to post this here first before opening a issue in case I was missing something.

My team is hoping to use the ADOS extension parameter 'abandonUnwantedPullRequests' to cleanup/abandon PRs that are not needed or is a older duplicate of a new existing PR. In the case where the PR sits to be reviewed due to other priorities. 

However, we've found that the parameter hasn't been cleaning up conflicting dependencies like the example below. Currently each of repo has a .NET source and test project so I'm wondering if that would be a problem with the following known issue [451](https://github.com/tinglesoftware/dependabot-azure-devops/issues/451).

Am I missing something here, or does abandonUnwantedPullRequests not cover my example below?

Currently using V1 Extension (Using V2 will require approval of Org)

Example:
Old: Bump MSTest.TestFramework from 3.4.3 to 3.5.1 // Should Abandon
New: Bump MSTest.TestFramework from 3.4.3 to 3.6.0 // Should Keep

Yaml Task
```
- task: dependabot@1
   displayName: 'Run Dependabot'
   inputs:
      setAutoComplete: false
      abandonUnwantedPullRequests: true
      targetRepositoryName: ${{ repoName }}
      useUpdateScriptvNext: true # Needed for private nuget feeds while testing
      extraEnvironmentVariables: 'DEPENDABOT_EXTRA_CREDENTIALS=$(registryCredentials);DEPENDABOT_TARGET_BRANCH=${{parameters.targetBranch}};DEPENDABOT_IGNORE_CONDITIONS=$(ignoreDependencies);DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=${{parameters.pullRequestLimit}}'
```
