### DISCUSSION TITLE
What's the easiest way to ignore a specific version/dependency, when you know you can't upgrade to it?

### DISCUSSION THREAD

**Discussion by semkeijsper** [mburumaxwell/paklo#1542] [Q&A] [answered]
We have multiple NuGet packages we can't upgrade to, for multiple different reasons. We are forced to use .NET 4.8 as we are programming an AutoCAD extension.

So when we decline a PR created by Dependabot, for example `xunit.runner.visualstudio@3.0.0`, Dependabot will happily create a new PR for `xunit.runner.visualstudio@3.0.1`. It will abandon the old PR, and reset any knowledge or comments about why the previous PR was rejected.

Would there be a possibility for Dependabot to remember the state of the previous PR of a certain package, and apply it to the one it newly created? 

On GitHub you can use [comment commands](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands), but I assume this isn't possible on Azure DevOps or is too complex to implement.

Just implementing a carry-over for the PR state would already be a big help.

If there's another way to manage this easily, please let me know.

**Comment by rhyskoedijk** [comment, marked as answer]
Unfortunately comment commands are not implemented currently;  It is tracked by https://github.com/tinglesoftware/dependabot-azure-devops/issues/101.

Recognising abandoned PRs and auto-ignoring them like GitHub does is something I would like to look in to, but isn't implemented yet either.

For now, to ignore packages, use the [`ignore` option in `dependabot.yml`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#ignore--). e.g.

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    ignore:
      # Ignore major version updates for all packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore xunit updates that are not patches
      - dependency-name: "xunit.*"
        update-types: ["version-update:semver-major","version-update:semver-major"]
      # Ignore xunit updates above v3.0.0
      - dependency-name: "xunit.*"
        versions:
          - ">=3.0.0"
```
