### DISCUSSION TITLE
Make masking (secrets) optional

### DISCUSSION THREAD

**Discussion by kzhuklinets** [mburumaxwell/paklo#1551] [Ideas]
Hi,

We are trying to migrate to dependabot@2 and as we use a self-hosted Azure DevOps, we are struggling with issues described in here https://github.com/tinglesoftware/dependabot-azure-devops/issues/1550, and the masking prevents from being sure regarding a root cause. If possible, could URLs be optional to be marked as secrets? https://github.com/tinglesoftware/dependabot-azure-devops/blob/873d4308e40561b31c8bfc714d304eace52f524b/extension/tasks/dependabotV2/index.ts#L38

**Comment by rhyskoedijk** [comment]
@mburumaxwell any thoughts on this? I could wrap the `setSecret` in a `if (tl.getVariable('System.Secrets')?.match(/true/i))` to disable this if the user really wants to, but that is another toggle.

**Reply by mburumaxwell** [reply]
It makes sense though I  do not know if there is an official reference to `System.Secrets` or it would be our own definition.

**Reply by rhyskoedijk** [reply]
I made it up, just as an example

**Reply by mburumaxwell** [reply]
We can work with it. A boolean input would be okay.

**Comment by mburumaxwell** [comment]
Added in https://github.com/tinglesoftware/dependabot-azure-devops/issues/1597, released in [1.44.0](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.44.0), and published in `1.44.0.1200`.

Example:

```yml
trigger: none # Disable CI trigger

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

variables:
  system.debug: 'true'

jobs:
- job: unprotected
  variables:
    System.Secrets: false

  steps:
  - task: dependabot@2
    inputs:
      skipPullRequests: true

- job: protected
  variables:
    System.Secrets: true

  steps:
  - task: dependabot@2
    inputs:
      skipPullRequests: true
```

Please test and get back.
