### DISCUSSION TITLE
Can't run Dependabot on Microsoft Hosted Agents due to high disc space demand

### DISCUSSION THREAD

**Discussion by Gemberkoekje** [mburumaxwell/paklo#1641] [Q&A]
I have a very similar issue as issue #1473 but as I'm not sure if it's an issue or something I can configure, I decided to start with a Q&A. 

I have a monorepo with around 40 solutions, totalling roughly 100 projects. As we are currently running renovate, they are mostly up to date.

The main issue I run into right now is that the disk fills up until it's full, and the pipeline fails after around half an hour.

I do see lots of copying happening, and I also suspect NuGet packages being redownloaded repeatedly. The log file is also over 300.000 lines long, which probably also doesn't help. I'm currently using the dependabot extension for azure, if it's better to use dependabot directly I'm open to try that, but I'd need some help setting that up.

My azure yaml looks as follows:
```
schedules:
  - cron: '0 0 * * *'
    displayName: 'Every Day'
    branches:
      include: [main]
    always: true

trigger: none

variables:
- name: pool
  value: work-pool-01
- name: demands
  value: WorkFolder -equals /mnt/storage/sdc/custom-work-folder
- name: WORK_NUGET_FEED_TOKEN
  value: $(System.AccessToken)

jobs:
  - job:
    timeoutInMinutes: 240
    workspace:
      clean: all
    pool:
      name: $(pool)
      demands:
      - $(demands)
    steps:
    - checkout: self
      clean: true
      path: s/mnt/storage/sdc/custom-work-folder/dependabot # This was an attempt to move some of the data to external disk to try and leave more disk space free on the agent
      workspaceRepo: true
      fetchDepth: 1
      fetchTags: false
      sparseCheckoutDirectories: services
    - task: dependabot@2
      inputs:
        DetailedLog: false # This doesn't have any effect, at least not in the dependabot task I'm using
        logFileVerbosity: quiet # This doesn't have any effect, at least not in the dependabot task I'm using
        skipPullRequests: true # I want to see it working before I have it start to make actual pull requests
        abandonUnwantedPullRequests: true
        commentPullRequests: true
        setAutoComplete: true
        mergeStrategy: 'squash'
        authorEmail: 'dependabot@tjip.com'
        authorName: 'dependabot'
```

My dependabot.yml looks as follows:
```
version: 2
registries:
  nuget-work-1:
    type: nuget-feed
    url: [url]
    username: [username]
    password: ${{ WORK_NUGET_FEED_TOKEN}}
  nuget-work-2:
    type: nuget-feed
    url: [url]
    username: [username]
    password: ${{ WORK_NUGET_FEED_TOKEN}}
  nuget-work-3:
    type: nuget-feed
    url: [url]
    username: [username]
    password: ${{ WORK_NUGET_FEED_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directories:
      - "services/*"
    registries:
     - nuget-work-1
     - nuget-work-2
     - nuget-work-3
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      major-work:
        applies-to: version-updates
        patterns:
          - "Work*"
        update-types:
          - "major"
```
