### ISSUE TITLE
git clone from the wrong host.

### ISSUE THREAD

**Issue by advision-digital** [mburumaxwell/paklo#1821]
**Describe the bug**

The Dependabot pipeline has recently stopped working. In the Git clone, the pipeline uses dev.azure.com instead of the domain of the Azure DevOps server.

**Pipeline configuration**
```yaml
stages:
- stage: update_dependencies
  jobs:
  - job:
    steps:
    - task: dependabot@2
      displayName: 'dependabot'
      inputs:
        setAutoComplete: true
        mergeStrategy: 'squash'
        autoApprove: true
        azureDevOpsAccessToken: '$(DEPENDABOT_ACCESS_TOKEN)'
```

**Expected behavior**
I expect that git clone is executed on the host of the Azure DevOps Server instead of dev.azure.com.

**Logs and screenshots**
2025/06/17 06:29:11 INFO Running command: git clone --no-tags --depth 1 --recurse-submodules --shallow-submodules https://dev.azure.com/DefaultCollection/internal/_git/Monitoring /home/dependabot/dependabot-updater/repo
```json
{
	"data": {
		"error-type": "job_repo_not_found",
		"error-details": {
			"message": "Cloning into '/home/dependabot/dependabot-updater/repo'...\nfatal: could not read Username for 'https://dev.azure.com': No such device or address\n\n"
		}
	},
	"type": "record_update_job_error"
}
```
**Extension (please complete the following information):**
 - Host:  Azure DevOps Server 2022
 - Version 19.225.34309.2 (AzureDevOps2022.1)
