### ISSUE TITLE
Dependabot has stopped finding nuget updates

### ISSUE THREAD

**Issue by cjda1** [mburumaxwell/paklo#1838]
### Categorization

- [x] This is not a permissions issue (Seek help at https://github.com/mburumaxwell/dependabot-azure-devops/discussions/1245)
- [x] This is an issue specific to Azure DevOps or this repository and does not belong in [dependabot-core](https://github.com/dependabot/dependabot-core).
Specific issues for dependabot are solved faster in the core repository. For example, why a package version is skipped.
Trying out this behaviour in the GitHub Hosted version can help you pinpoint where it lies.

- [ ] I have linked a public reproduction of the specific issue or none is required because the issue is not specific to me.
Please note that you can create a public organization/project and repository to show the issue. This tends to accelerate resolution.

### Steps to reproduce

1. Daily run of dependabot task in Azure devops pipeline **dependabot@2**.

### Expected behavior

Expecting the task to find updates to nuget packages. We have successfully used dependabot task in Azure Devops for some time, but recently it stopped finding any updates to our nuget packages, even though there exists ones (manually checking via Visual studio "Manage Packages for Solution". The pipeline completes with a green check mark ✅, so it does not report any error or such. We have not made any changes to our dependabot yml files so I figure its either a change to the dependabot@2 task or dependabot-core. Not sure.

### Logs and screenshots

**dependabot.yml file:**

```
version: 2
registries:
  nuget-azure-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/omitted-for-compliance-reasons/nuget/v3/index.json
    token: PAT:${{FEED_ACCESSTOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    target-branch: "main"
    open-pull-requests-limit: 15
    registries:
      - nuget-azure-devops
    groups:
      microsoft-aspnetcore:
        patterns:
          - "Microsoft.AspNetCore.*"
        update-types:
          - "major"
          - "minor"
          - "patch"

      microsoft-entityframeworkcore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
        update-types:
          - "major"
          - "minor"
          - "patch"
```

dependabot-pipelines.yml file:

```
name: Find-Nuget-Packages-To-Update-And-Create-Pull-Request

schedules:
  - cron: "0 5 * * 1-5"
    displayName: "Daily Automatic Dependabot Run"
    always: true
    branches:
      include:
        - main

trigger:
- none

pool: vmss-linux-swe

variables:
  - group: OmittedForComplianceReasons
  - name: DEPENDABOT_EXTRA_CREDENTIALS
    value: '[
              {
                "type": "nuget_feed",
                "token": "$(FEED_ACCESSTOKEN):",
                "url": "https://pkgs.dev.azure.com/omitted-for-compliance-reasons/nuget/v3/index.json",
              },
            ]'

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool: vmss-linux-swe
        steps:
          - task: dependabot@2
            displayName: 'Run Dependabot'
            inputs:
              setAutoComplete: true
              azureDevOpsAccessToken: $(GIT_ACCESSTOKEN)
```

### Extension Host

Azure DevOps

### Extension Version

2.53.2
